### ISSUE TITLE
v1.0.2 version is not release

### ISSUE THREAD

**Issue by cedarkuo** [tsroten/hanzidentifier#2]
Although [hanzidentifier](https://pypi.org/project/hanzidentifier/) on pypi was updated to v1.0.2, but still not add v1.0.2 tag and not create a v1.0.2 release on github.

So I'm wondering that could you also update v1.0.2 on github? Thanks.

**Comment by tsroten** [comment]
@cedarkuo Sure! Sorry for overlooking this. I've added the tag.
