### ISSUE TITLE
"着" is both valid as a Simplified and a Traditional character

### ISSUE THREAD

**Issue by shun-liang** [tsroten/hanzidentifier#5]
Hi, `hanzidentifier` identifies it as `SIMPLIFIED`.

```python
In [9]: hanzidentifier.identify("着")
Out[9]: 2
```

However, I think "着" is also a valid Traditional Chinese character, and is commonly used in Hong Kong.

Reference:
* http://chardb.iis.sinica.edu.tw/meancompare/8457/7740
* https://jonathanovsky.wordpress.com/2015/03/12/%E3%80%8C%E7%9D%80%E3%80%8D%E5%92%8C%E3%80%8C%E8%91%97%E3%80%8D%E4%B9%8B%E5%88%A5/

**Comment by cdown** [comment]
hanzidentifier uses CC-CEDICT through [zhon](https://github.com/tsroten/zhon) as the authoritative source of which character fits which category.

As such, you'd need to file this with CC-CEDICT: https://cc-cedict.org/wiki/todo:todo

**Comment by shun-liang** [comment]
@cdown Thanks for letting me know. I will file this to CC-CEDICT.
